FROM ubuntu:22.04

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

RUN apt update && apt upgrade -y
RUN apt install -y software-properties-common
RUN add-apt-repository universe
RUN apt install -y apt-utils gedit openssh-client git locales lsb-release gnupg2 curl jq tmux vim gnupg2 lsb-release zip iputils-ping net-tools

# Install ROS2 humble
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN export LANG=en_US.UTF-8

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt update && apt upgrade -y && apt install -y ros-humble-desktop ros-dev-tools python3-pip python3-colcon-common-extensions ros-humble-ros2bag ros-humble-rosbag2-storage-default-plugins ros-humble-rosbag2-storage-mcap ros-humble-pcl-ros ros-humble-image-common ros-humble-camera-info-manager ros-humble-cv-bridge ros-humble-image-transport ros-humble-diagnostic-updater ros-humble-sensor-msgs ros-humble-std-msgs ros-humble-geometry-msgs ros-humble-diagnostic-msgs ros-humble-image-transport ros-humble-compressed-image-transport
RUN pip3 install -U argcomplete

RUN mkdir -p /root/ros2_ws/src

RUN echo "" >> /root/.bashrc
RUN echo "### ros2" >> /root/.bashrc
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc
RUN echo "source ~/ros2_ws/install/setup.bash" >> /root/.bashrc
RUN echo "" >> /root/.bashrc
RUN echo "alias cs='cd ~/ros2_ws/src'" >> /root/.bashrc
RUN echo "alias cw='cd ~/ros2_ws'" >> /root/.bashrc
RUN echo "alias cm='cd ~/ros2_ws && colcon build --symlink-install --cmake-args -DBUILD_SHARED_LIBS=ON && source ~/.bashrc'" >> /root/.bashrc
RUN echo "" >> /root/.bashrc

RUN mkdir -p -m 0700 /root/.ssh && ssh-keyscan github.com >> /root/.ssh/known_hosts
RUN --mount=type=ssh git clone git@github.com:SOSLAB-IVC/ml_ros2.git /root/ros2_ws/src/ml_ros2
RUN --mount=type=ssh git clone git@github.com:SOSLAB-IVC/pylon_ros2.git /root/ros2_ws/src/pylon_ros2

COPY pylon_8.1.0-deb0_amd64.deb /root/pylon_8.1.0-deb0_amd64.deb
COPY codemeter_8.20.6558.501_amd64.deb /root/codemeter_8.20.6558.501_amd64.deb
COPY pylon-supplementary-package-for-blaze-1.7.2.f00d43816_amd64.deb /root/pylon-supplementary-package-for-blaze-1.7.2.f00d43816_amd64.deb 
RUN apt install -y /root/pylon_8.1.0-deb0_amd64.deb /root/codemeter_8.20.6558.501_amd64.deb /root/pylon-supplementary-package-for-blaze-1.7.2.f00d43816_amd64.deb

RUN apt update && apt upgrade -y

RUN echo "#!/bin/bash" >> /root/run_rgb.sh
RUN echo "ros2 launch /root/ros2_ws/src/pylon_ros2/pylon_ros2_camera_wrapper/launch/pylon_ros2_camera.launch.py" >> /root/run_rgb.sh
RUN chmod +x /root/run_rgb.sh

RUN echo "#!/bin/bash" >> /root/run_lidar.sh
RUN echo "ros2 launch /root/ros2_ws/src/ml_ros2/launch/mlx_launch.py" >> /root/run_lidar.sh
RUN chmod +x /root/run_lidar.sh

CMD ["/bin/bash"]
